# Generated by Django 5.0.6 on 2024-06-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shares", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp")),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "range_header",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="HTTP Range Header"
                    ),
                ),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shares.share"
                    ),
                ),
            ],
        ),
    ]
