# Generated by Django 5.0.6 on 2024-12-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shares", "0003_share_download_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="force_download",
            field=models.BooleanField(default=True, verbose_name="Force Downloading"),
        ),
    ]
