name: Package

on:
  push:
    tags: ['*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dpk2442/filelink
  TARGET_PLATFORMS: linux/amd64,linux/arm/v8,linux/arm/v7

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.TARGET_PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
